server.port=9052
spring.application.name=mediclaim-service

spring.datasource.url=jdbc:postgresql://43.205.24.208:5432/mediclaim_db
spring.datasource.username=postgres
spring.datasource.password=pgadmin
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maxLifetime=300000
spring.datasource.hikari.idleTimeout=60000
spring.datasource.hikari.validationTimeout=5000

spring.mail.host=mapi.cms.co.in
spring.mail.port=587
spring.mail.username=cdladmin@cms.co.in
spring.mail.password=Wsus@1354
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.from=cdladmin@cms.co.in
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.debug=true
